version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    secrets:
      - integration_flowdock_signature_key
      - integration_flowdock_token
    networks:
      - internal

secrets:
  integration_flowdock_signature_key:
    file: ./.balena/secrets/integration_flowdock_signature_key
  integration_flowdock_token:
    file: ./.balena/secrets/integration_flowdock_token
